export const defaultFinanceConfig = {
    initialWeek: 1,
    paycheckAmount: 500,
    startingBalance: 500,
    creditLimit: 500,
    tasks: [
        {
            id: 'T1',
            title: 'Rent Payment',
            amount: 100,
            dueWeek: 3,
            assignedBills: [],
            status: 'fixed',
        },
        {
            id: 'T2',
            title: 'Utilities',
            amount: 50,
            dueWeek: 2,
            assignedBills: [],
            status: 'fixed',
        },
        {
            id: 'T3',
            title: 'Groceries',
            amount: 80,
            dueWeek: 1,
            assignedBills: [],
            status: 'variable',
        },
        {
            id: 'T4',
            title: 'Internet Bill',
            amount: 60,
            dueWeek: 2,
            assignedBills: [],
            status: 'fixed',
        },
        {
            id: 'T5',
            title: 'Phone Bill',
            amount: 40,
            dueWeek: 1,
            assignedBills: [],
            status: 'fixed',
        },
    ],
    bills: [
        { id: 'b1', value: 100, type: 'cash' },
        { id: 'b2', value: 50, type: 'cash' },
        { id: 'b3', value: 10, type: 'cash' },
        { id: 'b4', value: 1, type: 'cash' },
        { id: 'cc1', value: 500, type: 'credit' },
    ],
};
